# .github/workflows/flutter-build.yml
name: Flutter Windows Build

# 🔥 必须定义事件触发器（即使被其他工作流调用）
on:
  workflow_call:  # 允许被其他工作流调用
    inputs:
      upload-artifact:
        type: boolean
        default: false
      upload-tag:
        type: string
        default: "latest"
