# .github/workflows/main.yml
name: Nightly Build

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  build-windows:
    # 🔥 正确引用方式（需包含完整路径）
    uses: ./.github/workflows/flutter-build.yml
    with:
      upload-artifact: true
      upload-tag: "nightly-v1"
